### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by yixtan** [ss098/payment-script#2]
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

请问现在是否依然可用呢？

**Comment by ss098** [comment]
目前仍然是可用的，请检查运行环境，这个提示信息是校验 SSL 证书失败。

**Comment by yixtan** [comment]
请问这个失败的原因该如何查？另外环境变量PAYMENT_SECERT要怎么设置？多谢。

**Comment by ss098** [comment]
你可以在运行的机子上访问 https://my.alipay.com/portal/i.htm 试试，看看是否仍然出现 SSL 错误。

如果仍然出现，可以考虑放弃检查 HTTPS 证书（这个行为是危险的），在 alipay.py 的 38 和 41 行加上参数 verify=False。

这个环境变量是你自行设定的一个值，可以任意设置。

**Comment by yixtan** [comment]
谢谢，找到问题原因了，用 Surge 抓 cookie 的时候，Surge 改了系统的 cert，恢复初始状态就好了。

**Comment by ss098** [comment]
😋
